esphome:
  name: esphome-web-70ace4
  friendly_name: ESPHome_Lights_Roof
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: Kurt
  password: Penis6969_
  manual_ip:
    static_ip: 192.168.99.52
    gateway: 192.168.99.1
    subnet: 255.255.255.0

light:
  - platform: fastled_clockless
    id: ws2815_strip
    name: "WS2815 LED Strip"
    chipset: WS2812B       # WS2815 uses similar timing to WS2812B/WS2811
    pin: GPIO4             # Change to the GPIO pin you’re using for data
    num_leds: 4           # Total number of LEDs in your strip
    rgb_order: RGB         # Common order for many addressable strips
    # Adjust the below to suit your preferences for color and brightness limits
    default_transition_length: 1s
    effects:
      - addressable_rainbow:
      - addressable_scan:
      - addressable_twinkle:
      - random:
      - strobe: