# Enable I2C communication
i2c:
  sda: 22
  scl: 21
  scan: true
  id: bus_a

# MPU6050 sensor integration
sensor:
  - platform: mpu6050
    address: 0x68
    update_interval: 1s
    accel_x:
      name: "MPU6500 Acceleration X"
      filters:
        - calibrate_linear:
            # Adjust these values as needed for calibration
            slope: 1.0
            offset: 0.0
    accel_y:
      name: "MPU6500 Acceleration Y"
      filters:
        - calibrate_linear:
            slope: 1.0
            offset: 0.0
    accel_z:
      name: "MPU6500 Acceleration Z"
      filters:
        - calibrate_linear:
            slope: 1.0
            offset: 0.0
    gyro_x:
      name: "MPU6500 Gyro X"
      filters:
        - calibrate_linear:
            slope: 1.0
            offset: 0.0
    gyro_y:
      name: "MPU6500 Gyro Y"
      filters:
        - calibrate_linear:
            slope: 1.0
            offset: 0.0
    gyro_z:
      name: "MPU6500 Gyro Z"
      filters:
        - calibrate_linear:
            slope: 1.0
            offset: 0.0
