esphome:
  name: esphome-web-480950
  friendly_name: esphome_web_480950
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: Kurt
  password: Penis6969_
  manual_ip:
    static_ip: 192.168.99.51
    gateway: 192.168.99.1
    subnet: 255.255.255.0

sensor:
  - platform: dht
    pin: GPIO4
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s